site_name: Solaar Documentation
theme:
  name: readthedocs
docs_dir: docs
nav:
  - Solaar: index.md
  - Capabilities: capabilities.md
  - Debian: debian.md
  - Devices: devices.md
  - Features: features.md
  - Translation: i18n.md
  - Implementation: implementation.md
  - Installation: installation.md
  - Rules: rules.md
  - Usage: usage.md

  - Developer Documentation: reference/developer_documentation.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - python -m pip install .
  - mermaid2
markdown_extensions:
  - pymdownx.superfences
