title: Solaar
description: Linux Device manager for the Logitech Unifying Receiver.
tagline: Linux Device manager for the Logitech Unifying Receiver.
owner: pwr-Solaar
owner_url: https://github.com/pwr-Solaar
repository: pwr-Solaar/Solaar
version: 1.0.1
show_downloads: false
encoding: utf-8
theme: jekyll-theme-slate